provider: "OpenAI"
llm_model: "gpt-4o"
embed_model: "text-embedding-3-large"
temperature: 0.2
max_tokens: 600
judge_weights:
  Clarity: 30
  Completeness: 25
  Constraint coverage: 20
  Testability: 15
  Safety: 10
